package com.composelib.catalog

enum class ThemeMode {
    Light,
    Dark,
}

data class ThemeColorTokens(
    val primary: String,
    val onPrimary: String,
    val primaryContainer: String,
    val onPrimaryContainer: String,
    val secondary: String,
    val onSecondary: String,
    val background: String,
    val onBackground: String,
    val surface: String,
    val onSurface: String,
    val surfaceVariant: String,
    val onSurfaceVariant: String,
    val outline: String,
    // ─── v2.0: Text hierarchy ────────────────────────────────
    val textPrimary: String,
    val textSecondary: String,
    val textTertiary: String,
    val textQuaternary: String,
    val textDisabled: String,
    val textHighlight: String,
    val textOnHighlight: String,
    // ─── v2.0: Icon hierarchy ────────────────────────────────
    val iconPrimary: String,
    val iconSecondary: String,
    val iconTertiary: String,
    val iconQuaternary: String,
    // ─── v2.0: Error / Warning ───────────────────────────────
    val errorRed: String,
    val errorRedContainer: String,
    val warningYellow: String,
    val warningOrange: String,
    val warningOrangeContainer: String,
    // ─── v2.0: Surface extensions ────────────────────────────
    val surfaceHighlight: String,
    val surfaceHighlightContainer: String,
    // ─── v2.0: Divider & Overlay ─────────────────────────────
    val divider: String,
    val dividerVariant: String,
    val pressOverlay: String,
)

data class ThemeTypographyTokens(
    val titleSizeSp: Int,
    val titleWeight: Int,
    val bodySizeSp: Int,
    val bodyWeight: Int,
    val captionSizeSp: Int,
    val captionWeight: Int,
)

data class ThemeSpacingTokens(
    val compactDp: Int,
    val regularDp: Int,
    val spaciousDp: Int,
    val sectionDp: Int,
)

data class ThemeShapeTokens(
    val cardCornerRadiusDp: Int,
    val mediaCornerRadiusDp: Int,
    val pillCornerRadiusDp: Int,
)

data class ThemeMediaTokens(
    val thumbnailAspectRatio: Float,
    val heroAspectRatio: Float,
    val overlayAlpha: Float,
)

data class ThemeFoundationTokens(
    val typography: ThemeTypographyTokens,
    val spacing: ThemeSpacingTokens,
    val shapes: ThemeShapeTokens,
    val media: ThemeMediaTokens,
)

data class ThemeDefinition(
    val key: String,
    val name: String,
    val mode: ThemeMode,
    val description: String,
    val colors: ThemeColorTokens,
    val foundation: ThemeFoundationTokens = defaultFoundation(),
)

object ThemeCatalog {
    fun defaultThemes(): List<ThemeDefinition> = listOf(
        ThemeDefinition(
            key = "editorial-light",
            name = "Editorial Light",
            mode = ThemeMode.Light,
            description = "Warm, gallery-like light theme.",
            colors = ThemeColorTokens(
                primary = "#1B3A57",
                onPrimary = "#FFFFFF",
                primaryContainer = "#D7E4F1",
                onPrimaryContainer = "#10253A",
                secondary = "#5C5A7D",
                onSecondary = "#FFFFFF",
                background = "#F7F4EE",
                onBackground = "#1D1B17",
                surface = "#FFFBF4",
                onSurface = "#1D1B17",
                surfaceVariant = "#E5E0D8",
                onSurfaceVariant = "#4A4540",
                outline = "#77726B",
                textPrimary = "#1D1B17",
                textSecondary = "#423F39",
                textTertiary = "#726C64",
                textQuaternary = "#B4AEA5",
                textDisabled = "#A6A098",
                textHighlight = "#1B3A57",
                textOnHighlight = "#FFFFFF",
                iconPrimary = "#1D1B17",
                iconSecondary = "#423F39",
                iconTertiary = "#726C64",
                iconQuaternary = "#B4AEA5",
                errorRed = "#BA1A1A",
                errorRedContainer = "#FFDAD6",
                warningYellow = "#B8860B",
                warningOrange = "#FF6B00",
                warningOrangeContainer = "#FFE0C2",
                surfaceHighlight = "#1B3A57",
                surfaceHighlightContainer = "#D7E4F1",
                divider = "#35312C",
                dividerVariant = "#544E47",
                pressOverlay = "#1A000000",
            ),
            foundation = defaultFoundation(),
        ),
        ThemeDefinition(
            key = "editorial-dark",
            name = "Editorial Dark",
            mode = ThemeMode.Dark,
            description = "Low-light editorial theme with softened contrast.",
            colors = ThemeColorTokens(
                primary = "#A7C4DD",
                onPrimary = "#0B1D2D",
                primaryContainer = "#183247",
                onPrimaryContainer = "#D7E4F1",
                secondary = "#B8B4D7",
                onSecondary = "#17162C",
                background = "#151311",
                onBackground = "#F2ECE2",
                surface = "#1D1A17",
                onSurface = "#F2ECE2",
                surfaceVariant = "#403B35",
                onSurfaceVariant = "#CFC7BA",
                outline = "#8E877E",
                textPrimary = "#F2ECE2",
                textSecondary = "#CFC9C0",
                textTertiary = "#9A938A",
                textQuaternary = "#666059",
                textDisabled = "#706A62",
                textHighlight = "#A7C4DD",
                textOnHighlight = "#0B1D2D",
                iconPrimary = "#F2ECE2",
                iconSecondary = "#CFC9C0",
                iconTertiary = "#9A938A",
                iconQuaternary = "#666059",
                errorRed = "#FFB4AB",
                errorRedContainer = "#93000A",
                warningYellow = "#FFCC00",
                warningOrange = "#FF9F0A",
                warningOrangeContainer = "#663C00",
                surfaceHighlight = "#A7C4DD",
                surfaceHighlightContainer = "#183247",
                divider = "#645D55",
                dividerVariant = "#8E877E",
                pressOverlay = "#1A000000",
            ),
            foundation = defaultFoundation(overlayAlpha = 0.18f),
        ),
        ThemeDefinition(
            key = "neon-arcade-dark",
            name = "Neon Arcade Dark",
            mode = ThemeMode.Dark,
            description = "High-energy cyber palette with sharp neon contrast.",
            colors = ThemeColorTokens(
                primary = "#33F1FF",
                onPrimary = "#001519",
                primaryContainer = "#01333A",
                onPrimaryContainer = "#9CFBFF",
                secondary = "#FF4FD8",
                onSecondary = "#22001A",
                background = "#0A0A12",
                onBackground = "#EAF3FF",
                surface = "#111221",
                onSurface = "#EAF3FF",
                surfaceVariant = "#1D1F35",
                onSurfaceVariant = "#B4BDD9",
                outline = "#5D6790",
                textPrimary = "#EAF3FF",
                textSecondary = "#C7D0DB",
                textTertiary = "#959DA7",
                textQuaternary = "#626972",
                textDisabled = "#6C737D",
                textHighlight = "#33F1FF",
                textOnHighlight = "#001519",
                iconPrimary = "#EAF3FF",
                iconSecondary = "#C7D0DB",
                iconTertiary = "#959DA7",
                iconQuaternary = "#626972",
                errorRed = "#FFB4AB",
                errorRedContainer = "#93000A",
                warningYellow = "#FFCC00",
                warningOrange = "#FF9F0A",
                warningOrangeContainer = "#663C00",
                surfaceHighlight = "#33F1FF",
                surfaceHighlightContainer = "#01333A",
                divider = "#3A3B4D",
                dividerVariant = "#5D6790",
                pressOverlay = "#1A000000",
            ),
            foundation = defaultFoundation(overlayAlpha = 0.26f).copy(
                typography = ThemeTypographyTokens(
                    titleSizeSp = 22,
                    titleWeight = 700,
                    bodySizeSp = 14,
                    bodyWeight = 450,
                    captionSizeSp = 12,
                    captionWeight = 600,
                ),
                shapes = ThemeShapeTokens(
                    cardCornerRadiusDp = 14,
                    mediaCornerRadiusDp = 12,
                    pillCornerRadiusDp = 999,
                ),
            ),
        ),
        ThemeDefinition(
            key = "forest-mist-light",
            name = "Forest Mist Light",
            mode = ThemeMode.Light,
            description = "Soft natural palette with calm earthy accents.",
            colors = ThemeColorTokens(
                primary = "#2D6A4F",
                onPrimary = "#FFFFFF",
                primaryContainer = "#CFEBDC",
                onPrimaryContainer = "#123526",
                secondary = "#A56A2A",
                onSecondary = "#FFFFFF",
                background = "#F3F6F1",
                onBackground = "#1E2A22",
                surface = "#FCFEFA",
                onSurface = "#1E2A22",
                surfaceVariant = "#E2EADF",
                onSurfaceVariant = "#46554B",
                outline = "#738378",
                textPrimary = "#1E2A22",
                textSecondary = "#454F47",
                textTertiary = "#7A827A",
                textQuaternary = "#B1B7AF",
                textDisabled = "#A4AAA2",
                textHighlight = "#2D6A4F",
                textOnHighlight = "#FFFFFF",
                iconPrimary = "#1E2A22",
                iconSecondary = "#454F47",
                iconTertiary = "#7A827A",
                iconQuaternary = "#B1B7AF",
                errorRed = "#BA1A1A",
                errorRedContainer = "#FFDAD6",
                warningYellow = "#B8860B",
                warningOrange = "#FF6B00",
                warningOrangeContainer = "#FFE0C2",
                surfaceHighlight = "#2D6A4F",
                surfaceHighlightContainer = "#CFEBDC",
                divider = "#353F37",
                dividerVariant = "#546258",
                pressOverlay = "#1A000000",
            ),
            foundation = defaultFoundation(overlayAlpha = 0.14f).copy(
                spacing = ThemeSpacingTokens(
                    compactDp = 10,
                    regularDp = 14,
                    spaciousDp = 18,
                    sectionDp = 26,
                ),
                shapes = ThemeShapeTokens(
                    cardCornerRadiusDp = 24,
                    mediaCornerRadiusDp = 18,
                    pillCornerRadiusDp = 999,
                ),
            ),
        ),
        ThemeDefinition(
            key = "imperial-lux-dark",
            name = "Imperial Lux Dark",
            mode = ThemeMode.Dark,
            description = "Luxury editorial dark mode with deep navy and gold accents.",
            colors = ThemeColorTokens(
                primary = "#D4AF37",
                onPrimary = "#1E1500",
                primaryContainer = "#4A3A10",
                onPrimaryContainer = "#FCECB5",
                secondary = "#8FA2FF",
                onSecondary = "#09123D",
                background = "#101319",
                onBackground = "#F0EEE9",
                surface = "#171C24",
                onSurface = "#F0EEE9",
                surfaceVariant = "#2A313D",
                onSurfaceVariant = "#C2C8D6",
                outline = "#7D8699",
                textPrimary = "#F0EEE9",
                textSecondary = "#CCCAC5",
                textTertiary = "#979591",
                textQuaternary = "#63615E",
                textDisabled = "#6E6C68",
                textHighlight = "#D4AF37",
                textOnHighlight = "#1E1500",
                iconPrimary = "#F0EEE9",
                iconSecondary = "#CCCAC5",
                iconTertiary = "#979591",
                iconQuaternary = "#63615E",
                errorRed = "#FFB4AB",
                errorRedContainer = "#93000A",
                warningYellow = "#FFCC00",
                warningOrange = "#FF9F0A",
                warningOrangeContainer = "#663C00",
                surfaceHighlight = "#D4AF37",
                surfaceHighlightContainer = "#4A3A10",
                divider = "#474C55",
                dividerVariant = "#7D8699",
                pressOverlay = "#1A000000",
            ),
            foundation = defaultFoundation(overlayAlpha = 0.22f).copy(
                typography = ThemeTypographyTokens(
                    titleSizeSp = 21,
                    titleWeight = 650,
                    bodySizeSp = 14,
                    bodyWeight = 420,
                    captionSizeSp = 12,
                    captionWeight = 550,
                ),
                shapes = ThemeShapeTokens(
                    cardCornerRadiusDp = 18,
                    mediaCornerRadiusDp = 14,
                    pillCornerRadiusDp = 999,
                ),
            ),
        ),
        ThemeDefinition(
            key = "ec-hmi-light",
            name = "EC HMI Light",
            mode = ThemeMode.Light,
            description = "Automotive HMI light theme — iOS-style neutral grey system with blue accent.",
            colors = ThemeColorTokens(
                primary = "#0088FF",
                onPrimary = "#FFFFFF",
                primaryContainer = "#D6ECFF",
                onPrimaryContainer = "#001D36",
                secondary = "#787880",
                onSecondary = "#FFFFFF",
                background = "#FFFFFF",
                onBackground = "#000000",
                surface = "#F2F2F7",
                onSurface = "#000000",
                surfaceVariant = "#E5E5EA",
                onSurfaceVariant = "#48484A",
                outline = "#8E8E93",
                textPrimary = "#FF000000",
                textSecondary = "#D9000000",
                textTertiary = "#99000000",
                textQuaternary = "#40000000",
                textDisabled = "#4D000000",
                textHighlight = "#FF0088FF",
                textOnHighlight = "#FFFFFFFF",
                iconPrimary = "#FF000000",
                iconSecondary = "#D9000000",
                iconTertiary = "#99000000",
                iconQuaternary = "#40000000",
                errorRed = "#FF3B30",
                errorRedContainer = "#FFDAD6",
                warningYellow = "#B8860B",
                warningOrange = "#FF6B00",
                warningOrangeContainer = "#FFE0C2",
                surfaceHighlight = "#FF0088FF",
                surfaceHighlightContainer = "#FFD6ECFF",
                divider = "#33787880",
                dividerVariant = "#52787880",
                pressOverlay = "#1A000000",
            ),
            foundation = defaultFoundation(overlayAlpha = 0.15f).copy(
                typography = ThemeTypographyTokens(
                    titleSizeSp = 22,
                    titleWeight = 600,
                    bodySizeSp = 16,
                    bodyWeight = 300,
                    captionSizeSp = 12,
                    captionWeight = 300,
                ),
                spacing = ThemeSpacingTokens(
                    compactDp = 10,
                    regularDp = 16,
                    spaciousDp = 20,
                    sectionDp = 28,
                ),
                shapes = ThemeShapeTokens(
                    cardCornerRadiusDp = 24,
                    mediaCornerRadiusDp = 18,
                    pillCornerRadiusDp = 999,
                ),
            ),
        ),
        ThemeDefinition(
            key = "ec-hmi-dark",
            name = "EC HMI Dark",
            mode = ThemeMode.Dark,
            description = "Automotive HMI dark theme — neutral grey system with bright blue accent for low-light driving.",
            colors = ThemeColorTokens(
                primary = "#0091FF",
                onPrimary = "#001D36",
                primaryContainer = "#00325A",
                onPrimaryContainer = "#D6ECFF",
                secondary = "#787880",
                onSecondary = "#FFFFFF",
                background = "#000000",
                onBackground = "#FFFFFF",
                surface = "#1C1C1E",
                onSurface = "#FFFFFF",
                surfaceVariant = "#2C2C2E",
                onSurfaceVariant = "#AEAEB2",
                outline = "#636366",
                textPrimary = "#FFFFFFFF",
                textSecondary = "#E6FFFFFF",
                textTertiary = "#99FFFFFF",
                textQuaternary = "#40FFFFFF",
                textDisabled = "#4DFFFFFF",
                textHighlight = "#FF0091FF",
                textOnHighlight = "#FFFFFFFF",
                iconPrimary = "#FFFFFFFF",
                iconSecondary = "#E6FFFFFF",
                iconTertiary = "#99FFFFFF",
                iconQuaternary = "#40FFFFFF",
                errorRed = "#FF453A",
                errorRedContainer = "#93000A",
                warningYellow = "#FFCC00",
                warningOrange = "#FF9F0A",
                warningOrangeContainer = "#663C00",
                surfaceHighlight = "#FF0091FF",
                surfaceHighlightContainer = "#FF00325A",
                divider = "#52787880",
                dividerVariant = "#52787880",
                pressOverlay = "#1A000000",
            ),
            foundation = defaultFoundation(overlayAlpha = 0.25f).copy(
                typography = ThemeTypographyTokens(
                    titleSizeSp = 22,
                    titleWeight = 600,
                    bodySizeSp = 16,
                    bodyWeight = 300,
                    captionSizeSp = 12,
                    captionWeight = 300,
                ),
                spacing = ThemeSpacingTokens(
                    compactDp = 10,
                    regularDp = 16,
                    spaciousDp = 20,
                    sectionDp = 28,
                ),
                shapes = ThemeShapeTokens(
                    cardCornerRadiusDp = 24,
                    mediaCornerRadiusDp = 18,
                    pillCornerRadiusDp = 999,
                ),
            ),
        ),
    )
}

private fun defaultFoundation(
    overlayAlpha: Float = 0.12f,
): ThemeFoundationTokens = ThemeFoundationTokens(
    typography = ThemeTypographyTokens(
        titleSizeSp = 20,
        titleWeight = 600,
        bodySizeSp = 14,
        bodyWeight = 400,
        captionSizeSp = 12,
        captionWeight = 500,
    ),
    spacing = ThemeSpacingTokens(
        compactDp = 8,
        regularDp = 12,
        spaciousDp = 16,
        sectionDp = 24,
    ),
    shapes = ThemeShapeTokens(
        cardCornerRadiusDp = 20,
        mediaCornerRadiusDp = 16,
        pillCornerRadiusDp = 999,
    ),
    media = ThemeMediaTokens(
        thumbnailAspectRatio = 4f / 3f,
        heroAspectRatio = 16f / 9f,
        overlayAlpha = overlayAlpha,
    ),
)

/**
 * Alpha-composite [fg] over [bg] at the given opacity.
 *
 * Both colors must be in `#RRGGBB` format. Returns a `#RRGGBB` string with the
 * pre-multiplied result, useful for computing semantic token defaults from a
 * theme's base palette.
 */
fun blend(fg: String, bg: String, fgAlpha: Float): String {
    val fgR = fg.substring(1, 3).toInt(16)
    val fgG = fg.substring(3, 5).toInt(16)
    val fgB = fg.substring(5, 7).toInt(16)
    val bgR = bg.substring(1, 3).toInt(16)
    val bgG = bg.substring(3, 5).toInt(16)
    val bgB = bg.substring(5, 7).toInt(16)
    val a = fgAlpha.coerceIn(0f, 1f)
    val r = (fgR * a + bgR * (1 - a)).toInt().coerceIn(0, 255)
    val g = (fgG * a + bgG * (1 - a)).toInt().coerceIn(0, 255)
    val b = (fgB * a + bgB * (1 - a)).toInt().coerceIn(0, 255)
    return "#" +
        r.toString(16).padStart(2, '0').uppercase() +
        g.toString(16).padStart(2, '0').uppercase() +
        b.toString(16).padStart(2, '0').uppercase()
}
